version: '3.8'

services:
  backend:
    build: ./backend
    container_name: gulp-backend
    ports:
      - "8000:8000"
    volumes:
      - gulp-data:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: gulp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=/api

volumes:
  gulp-data:
    driver: local
