services:
  # Frontend service
  - type: web
    name: gulp-job-viewer-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: gulp-job-viewer-backend
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend service
  - type: web
    name: gulp-job-viewer-backend
    env: python
    buildCommand: cd backend && ./render-build.sh
    startCommand: cd backend && gunicorn -w 4 -k uvicorn.workers.UvicornWorker scraper:app
    envVars:
      - key: PYTHONPATH
        value: ./backend
      - key: DATA_DIR
        value: ./data
      - key: FRONTEND_URL
        fromService:
          type: web
          name: gulp-job-viewer-frontend
          envVarKey: RENDER_EXTERNAL_URL
